INSERT INTO catalogues_produits (
  organization_id,
  categorie,
  nom,
  description,
  fournisseur,
  prix_mensuel,
  engagement_mois,
  caracteristiques,
  tags,
  est_produit_base,
  actif
) VALUES
  (NULL, 'mobile', 'Forfait Pro 50Go', 'Forfait mobile professionnel avec 50Go de data', 'Orange Business',
   19.99, 12,
   '{"data_go": 50, "appels_illimites": true, "sms_illimites": true, "international": ["Europe", "DOM-TOM"]}'::jsonb,
   ARRAY['professionnel', 'pme', 'economique'], true, true),
  (NULL, 'mobile', 'Forfait Pro 100Go', 'Forfait mobile professionnel avec 100Go de data', 'Orange Business',
   29.99, 12,
   '{"data_go": 100, "appels_illimites": true, "sms_illimites": true, "international": ["Europe", "DOM-TOM", "USA"]}'::jsonb,
   ARRAY['professionnel', 'pme', 'premium'], true, true),
  (NULL, 'mobile', 'Forfait Pro Illimité', 'Forfait mobile professionnel data illimitée', 'Orange Business',
   39.99, 12,
   '{"data_go": "illimité", "appels_illimites": true, "sms_illimites": true, "international": ["Monde"]}'::jsonb,
   ARRAY['professionnel', 'premium', 'grands-comptes'], true, true),
  (NULL, 'mobile', 'Forfait Essentiel 20Go', 'Forfait économique pour collaborateurs', 'SFR Business',
   14.99, 12,
   '{"data_go": 20, "appels_illimites": true, "sms_illimites": true}'::jsonb,
   ARRAY['professionnel', 'economique', 'tpe'], true, true),
  (NULL, 'internet', 'Fibre Pro 500Mb', 'Connexion fibre optique professionnelle 500Mb/s', 'Orange Pro',
   49.99, 12,
   '{"debit_down_mb": 500, "debit_up_mb": 500, "technologie": "fibre", "ip_fixe": true, "gtie_temps_retablissement": "4h"}'::jsonb,
   ARRAY['professionnel', 'pme', 'performance'], true, true),
  (NULL, 'internet', 'Fibre Pro 1Gb', 'Connexion fibre optique professionnelle 1Gb/s symétrique', 'Orange Pro',
   79.99, 12,
   '{"debit_down_mb": 1000, "debit_up_mb": 1000, "technologie": "fibre", "ip_fixe": true, "gtie_temps_retablissement": "4h"}'::jsonb,
   ARRAY['professionnel', 'premium', 'grands-comptes'], true, true),
  (NULL, 'internet', 'SDSL 10Mb', 'Connexion SDSL symétrique garantie', 'SFR Business',
   99.99, 24,
   '{"debit_down_mb": 10, "debit_up_mb": 10, "technologie": "sdsl", "debit_garanti": true, "gtie_temps_retablissement": "4h"}'::jsonb,
   ARRAY['professionnel', 'premium', 'critiques'], true, true),
  (NULL, 'fixe', 'Trunk SIP 10 canaux', 'Trunk SIP professionnel 10 canaux simultanés', 'OVH Telecom',
   29.99, 12,
   '{"canaux_simultanees": 10, "appels_illimites": true, "destinations": ["France", "fixes Europe"], "portabilite_incluse": true}'::jsonb,
   ARRAY['professionnel', 'pme', 'voip'], true, true),
  (NULL, 'fixe', 'Trunk SIP 30 canaux', 'Trunk SIP professionnel 30 canaux simultanés', 'OVH Telecom',
   79.99, 12,
   '{"canaux_simultanes": 30, "appels_illimites": true, "destinations": ["France", "Europe", "USA"], "portabilite_incluse": true}'::jsonb,
   ARRAY['professionnel', 'premium', 'callcenter'], true, true),
  (NULL, 'equipement', 'Téléphone IP Yealink T43U', 'Téléphone IP professionnel écran couleur', 'Yealink',
   8.99, 0,
   '{"type": "telephone_ip", "ecran": "couleur 2.7\"", "nb_comptes_sip": 12, "poe": true}'::jsonb,
   ARRAY['equipement', 'voip', 'bureautique'], true, true),
  (NULL, 'equipement', 'Routeur 4G/5G Backup', 'Routeur de secours 4G/5G professionnel', 'Cisco',
   15.99, 0,
   '{"type": "routeur_backup", "connectivite": "4G/5G", "ethernet_ports": 4, "failover_auto": true}'::jsonb,
   ARRAY['equipement', 'backup', 'resilience'], true, true);
